In [7]:
def get_winner(points,tiled,width,height):
    score_1=culsco(points,tiled,width,height)
    reverse_one_two(tiled,width,height)
    score_2=culsco(points,tiled,width,height)
    reverse_one_two(tiled,width,height)
    if score_1>score_2:
        return 1#勝ち
    elif score_1<score_2:
        return -1#負け
    else:
        return 0#引き分け

In [1]:
import numpy as np
one=np.ones((3,4),dtype=int)
zero=np.zeros(10,dtype=int)
zero_h=np.zeros(10)
print(one)
print(zero)
print(zero_h)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[0 0 0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
def get_winner2(points,tiled,width,height):
    dif=get_difference(points,tiled,width,height)
    if dif>0:
        return "win"#sign あとで考える
    elif dif<0:
        return "lose"
    else:
        return "draw"

In [4]:
def get_difference(points,tiled,width,height):
    score_1=culsco(points,tiled,width,height)
    reverse_one_two(tiled,width,height)
    score_2=culsco(points,tiled,width,height)
    reverse_one_two(tiled,width,height)
    return score_1-score_2

In [ ]:
def reverse_one_two(tiled,width,height):#１と2の交換
    for i in range(height):
        for j in range(width):
            if tiled[i][j]==1:
                tiled[i][j]=2
            if tiled[i][j]==2:
                tiled[i][j]=1

In [3]:
def culsco(points,tiled,width,height):
    tl=cir2(tiled,width,height)
    score=0
    for i in range(height):
        for j in range(width):
            if tl[i][j]==4:
                score+=abs(points[i][j])
            if tl[i][j]==9:
                score+=points[i][j]
    return score

In [8]:
def culsco2(points,tiled,width,height):
    tl=cir2(tiled,width,height)
    score=[0,0]
    for i in range(height):
        for j in range(width):
            if tl[i][j]==4:
                score[1]+=abs(points[i][j])
            if tl[i][j]==9:
                score[0]+=points[i][j]
    return score

In [2]:
 def cir2(tiled,width,height):
    c=[]
    for i in range(height):
        o=[]
        for n in range(width):
            o.append(0)
        c.append(o)
    for i in range(height):
        for n in range(width):
            if tiled[i][n]==1:
                c[i][n]=9
                for k in range(width):
                    if k+1>n:
                        break
                    elif tiled[i][n-k-1]==1:
                        break
                    c[i][n-k-1]+=1
                for k in range(width):
                    if n+k+1>=width:
                        break
                    elif tiled[i][n+k+1]==1:
                        break
                    c[i][n+k+1]+=1
                for k in range(height):
                    if k+1>i:
                        break
                    elif tiled[i-k-1][n]==1:
                        break
                    c[i-k-1][n]+=1
                for k in range(height):
                    if i+k+1>=height:
                        break
                    elif tiled[i+k+1][n]==1:
                        break
                    c[i+k+1][n]+=1
    if not c[height-1][width-1]==9:
        c[height-1][width-1]=0
    if not c[height-1][0]==9:
        c[height-1][0]=0
    if not c[0][width-1]==9:
        c[0][width-1]=0
    if not c[0][0]==9:
        c[0][0]=0
    for s in range(width*height):
        count_exe=0
        for n in range(height):
            for i in range(width):
                if c[n][i]<4:
                    if n-1>=0:
                        if 0<c[n-1][i]<9:
                            c[n-1][i]=0
                            count_exe+=1
                    if i-1>=0:
                        if 0<c[n][i-1]<9:
                            c[n][i-1]=0
                            count_exe+=1
                    if n+1<len(b):
                        if 0<c[n+1][i]<9:
                            c[n+1][i]=0
                            count_exe+=1
                    if i+1<len(b[n]):
                        if 0<c[n][i+1]<9:
                            c[n][i+1]=0
                            count_exe+=1
        if count_exe==0:
            break
    return c